language: go

go:
  - 1.8
  - 1.9
  - tip

go_import_path: gopkg.in/corvus-ch/shamir.v1

script:
  - go test -coverprofile=coverage.txt -covermode=atomic -v .

after_success:
  - bash <(curl -s https://codecov.io/bash)
